USE [bookrentalshop]
GO

/****** Object:  Table [dbo].[divtbl]    Script Date: 2021-07-20 ¿ÀÈÄ 12:34:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[divtbl](
	[Division] [varchar](8) NOT NULL,
	[Names] [nvarchar](45) NULL,
PRIMARY KEY CLUSTERED 
(
	[Division] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


